* Suomalainen kalenteri

*Suomalaiset merkkipäivät Emacsin kalenteriin* (Finnish national and
Christian holidays for Emacs's calendar)

** Tietoja

=suomalainen-kalenteri.el= on ohjelma tai asetustiedosto, jonka avulla
[[http://www.gnu.org/software/emacs/][Emacs]]-tekstieditorin kalenteriin saadaan suomalaiset merkkipäivät.
Kalenteriin tulevat kaikki viralliset merkkipäivät sekä joitakin muita
vakiintuneita merkkipäiviä kuten /aprillipäivä/, /Lucian päivä/ ja
eräitä Ahvenanmaan merkkipäiviä.

** Asentaminen

Suomalainen kalenteri tulee käyttöön, kun tiedosto
=suomalainen-kalenteri.el= ladataan ja sen sisältö evaluoidaan. Lienee
järkevintä ladata se aina automaattisesti, kun Emacsin =calendar=-osa
ladataan. Emacsin käynnistystiedostoon =~/.emacs= voi laittaa
esimerkiksi seuraavanlaisen rivin:

#+BEGIN_SRC emacs-lisp
  (eval-after-load 'calendar
    '(load "~/hakemistopolku/suomalainen-kalenteri.el" t t))
#+END_SRC

** Lähdekoodi

Ohjelman lähdekoodi ja tämä esittelyteksti on ladattavissa osoitteesta
<[[https://github.com/tlikonen/suomalainen-kalenteri]]>.

** Tekijä ja tekijänoikeus

Tekijä: Teemu Likonen <tlikonen@iki.fi>

Tämä ohjelma on yleistä omaisuutta, ja se on siten vapaa
tekijänoikeuksista. Ohjelmaa levitetään siinä toivossa, että siitä on
hyötyä muille. Ohjelman tekijä ei anna mitään takuuta ohjelman
toiminnasta, ei edes lupausta, että se sopii johonkin tiettyyn
käyttötarkoitukseen.
